Repository ColumbiaOSS/project-proposals-s2023, pull requests merged in 2023-05, with the labels that each got.

#582 HW8: Add in Contribution 2 Link to Profile and Updated Project Page
  projects/python/usau-scraper.md
  students/eem2188.md
Labels: HW8

#577 HW8: Added contribution link and proposals prep
  projects/python/easierscrape.md
  students/dag2226.md
Labels: HW8

#576 Made HW8 fixes to personal and project markdown files.
  projects/python/copypaster.md
  projects/python/prettycopy.md
  students/aeg2225.md
Labels: HW8

#579 Update shapely.md
  projects/python/autogpt.md
  projects/python/shapely.md
Labels: HW6

#578 First Contribution
  students/ks3651.md
Labels: HW6

#600 Update spotify.md
  projects/python/spotify.md
Labels: HW8

#598 HW8: add badges to project file, add contribution to student file
  projects/python/pro-football-reference-web-scraper.md
  students/mjk2244.md
Labels: HW8

#594 HW8: Added 2nd contribution
  students/ek3192.md
Labels: HW8

#589 Resolving contribute PR issue
  students/im2594.md
Labels: HW8

#592 jp4013 - Markdowns Updated
  projects/javascript/chatGPTCoverLetterGenerator.md
  projects/python/chatGPTCoverLetterGenerator.md
  students/jp4013.md
Labels: HW8

#586 HW8: added 2nd contribution & badges
  projects/python/web-scraper-python.md
  students/kk3610.md
Labels: HW8

#588 HW8: Add new contributions for Yash and project badges
  projects/scala/shiva.md
  students/yd2590.md
Labels: HW8

#580 Contribution pull request link
  students/dz2428.md
Labels: HW6

#587 HW8: Added finalized info for student/project readme
  projects/python/bulk-mv.md
  students/ag4219.md
Labels: HW8

#585 HW 8 contribution
  students/ntb2135.md
Labels: HW8

#608 more pruning
  projects/python/latex-generator.md
  students/ss5946.md
Labels: internal

#607 HW8: Added second contribution
  students/ma4338.md
Labels: HW8

#609 HW8: Added required badges
  projects/python/terminal-history.md
Labels: HW8

#660 Updated age3d.md with Badges & Added 2nd Contrib to ac5003.md
  projects/python/age3d.md
  students/ac5003.md
Labels: HW8

#659 HW8: add badges to project markdown
  projects/javascript/algorithm-lovers.md
Labels: HW8

#654 Updated student and project information
  projects/python/insta-captions.md
  students/dc3448.md
Labels: HW8

#652 HW8: Add badges to project markdown (sst2147)
  projects/python/see-algo.md
Labels: HW8

#648 HW8 second contribution and update project markdown
  projects/python/splotify.md
  students/cc4655.md
Labels: HW8

#651 HW8: add contribution link and update md files
  projects/python/polling-bot.md
  students/grn2112.md
Labels: HW8

#647 HW8: add contribution and update markdown files
  projects/python/FinRL.md
  projects/python/crypto-trading.md
  students/zx2325.md
Labels: HW8

#644 added si2400 contribution 2
  projects/python/flask-blog.md
  students/si2400.md
Labels: HW8

#642 hw8 - updated yw3960.md
  projects/python/action-react.md
  students/yw3960.md
Labels: HW8

#641 HW8
  projects/typescript/judgemental.md
  students/an3056.md
Labels: HW8

#640 [HW8] Add second project contribution
  students/ua2182.md
Labels: HW8

#638 Update yy3131.md
  students/yy3131.md
Labels: HW8

#637 Add contribution #2 to scb2197.md
  students/scb2197.md
Labels: HW8

#636 Hw8: Added contribution pr and badges
  projects/javascript/custoplayer.md
  students/ea2905.md
Labels: HW8

#631 all changes for hw8
  projects/python/converter.md
  projects/python/converterpro.md
  students/los2119.md
Labels: HW8

#627 im2594: HW8
  projects/javascript/mongo-db-wrapper.md
  students/im2594.md
Labels: HW8

#622 Hw8 (hj2589): Add project badges and PR link to second contribution
  projects/python/pynrm.md
  students/hj2589.md
Labels: HW8

#621 Added link to my second contribution
  students/ala2201.md
Labels: HW8

#620 HW8: Add additional project badges for mabby
  projects/python/mabby.md
Labels: HW8

#619 HW8: Add external contribution PR links
  projects/python/mdformat.md
  students/ew2664.md
Labels: HW8

#612 HW8 fk2421: Updated project and personal markdown files, included HW8…
  projects/javascript/domainLoggerDeleteTabs.md
  students/fk2421.md
Labels: HW8

#611 HW8: personal and project markdown file update
  projects/python/palettes.md
  students/ys3593.md
Labels: HW8

#616 HW6: Add PyPi and contribution links
  students/tz2294.md
Labels: HW6

#661 Added HW8 Contribution plus updated personal readme
  projects/python/sec-web-scraper.md
  students/oko2107.md
Labels: HW8

#653 [hw8] add badges
  projects/python/openai-game-translator.md
Labels: HW8

#662 [hw8] added second contribution
  students/yx2729.md
Labels: HW8

#664 Update xs2421.md
  students/xs2421.md
Labels: HW8

#665 Update FinRL-paper_trading-sun.md
  projects/python/FinRL-paper_trading-sun.md
Labels: HW8

#666 Hw8 - Updated Project and Students MD
  projects/python/stixx.md
  students/mg4145.md
Labels: HW8

#668 hw8
  projects/python/autogpt.md
  projects/python/polysplit.md
  students/dz2428.md
Labels: HW8

#669 HW8: kz2442
  projects/python/pyvts.md
  students/kz2442.md
Labels: HW8

#674 Added Second Contribution PR Link + Badges
  projects/python/vocab-extension.md
  students/aj2604.md
Labels: HW8

#675 HW8: Added contribution link to profile page
  students/nhc2117.md
Labels: HW8

#677 added badges and author. Final Project Submission!?
  projects/python/no-teg.md
Labels: HW8

#678 Adding Contribution PR Link to .md file HW8
  students/eac2277.md
Labels: HW8

#681 hw8 submission
  projects/python/pynixconfig.md
  students/sn2865.md
Labels: HW8

#682 HW8: Update wdw2117.md
  students/wdw2117.md
Labels: HW8

#685 HW8: Update and rename fantasy-football.md to fantasyfootball-crawler.md
  projects/python/fantasy-football.md
  projects/python/fantasyfootball-crawler.md
Labels: HW8

#671 HW6 and HW8: Add two contribution PR links to cg3356.md
  students/cg3356.md
Labels: HW6

#667 HW6 contribution
  students/rp3111.md
Labels: HW6

#699 Added HW8 contribution, improved project description, and added badges
  projects/python/Augmentum.md
  projects/python/image_augmentation.md
  students/kk3084.md
Labels: HW8

#687 HW8: Update and rename disease-spread.md to epispread.md
  projects/python/disease-spread.md
  projects/python/epispread.md
  students/scb2197.md
Labels: HW8

#630 HW6&HW8: Update profile
  projects/solidity/poseidon-sol.md
  students/yn2411.md
Labels: HW6

#656 afs2185 - hw8
  projects/cpp/multithreading.md
  students/afs2185.md
Labels: HW8

#689 el3030 HW8
  projects/python/splitinerary.md
  students/el3030.md
Labels: HW8

#690 Fix broken license badge (HW8)
  projects/python/clip_bbox.md
Labels: HW8

#691 Final: Fixed build status badge link and a minor typo
  projects/python/ez-parse.md
  students/ss5945.md
Labels: HW8

#713 Final: jm5025 added badge & contribution
  projects/python/mctk.md
  students/jm5025.md
Labels: HW8

#712 HW8: 2nd contribution link and badges
  projects/python/nikefy.md
  students/cgr2134.md
Labels: HW8

#710 add pypi user link
  students/uyo2000.md
Labels: HW6

#708 HW8:sb4696 added new contributions
  projects/python/QuickReaderPDF.md
  students/sb4696.md
Labels: HW8

#692 Update rp3111.md with HW8 Contribution
  students/rp3111.md
Labels: HW8

#709 Completed HW6
  students/tc3117.md
Labels: HW6

#693 added contribution link
  students/dme2136.md
Labels: HW8

#694 added badges
  projects/python/soccer-api-wrapper.md
Labels: HW8

#695 Update mws2170.md to include npmjs account
  students/mws2170.md
Labels: HW6

#696 Added HW8 contributions to the dtw-sofar repo
  students/aem2283.md
Labels: HW8

#701 Added badges and required links
  students/mw3071.md
Labels: HW8

#698 [HW 8 / Prep] Improved project description and added badges
  projects/python/multi-scale-expansion.md
Labels: HW8

#704 HW6 & 8- Add Pypi and First Project Contributions + Second Contributions and proposals
  projects/python/seven_wonders.md
  students/pd2654.md
Labels: HW6, HW8

#705 updated project with badges and slot for contribution
  projects/python/osd-slides.md
  students/kk3528.md
Labels: HW8

#702 HW8: Added badges to project page and added contribution
  projects/python/tone-reader.md
  students/ddn2115.md
Labels: HW8

#722 Hw8: Readme.md update with new project.md
  projects/python/ranking.py.md
  students/sa3883.md
  students/scranking.md
Labels: HW8

#723 HW8: Contributions and .md file updates
  projects/javascript/arttime.md
  projects/python/wes_palette.md
  students/au2232.md
Labels: HW8

#717 Homework 8 - Edit proposal and personal Markdown
  projects/python/itzma-lint.md
  students/tc3117.md
Labels: HW8

#707 HW8 Updated PR
  projects/python/spotify_to_apple.md
  students/baa2159.md
Labels: HW8

#703 Update cn2521.md
  students/cn2521.md
Labels: HW8

#632 HW8 update readme and project markdown for last homework
  projects/python/DirectReport.md
  students/cdw2146.md
Labels: HW8

#271 HW2 add link
  projects/python/pytorch-nlp-chatbot.md
  projects/python/pytorch-nlp.md
  students/yh3575.md
Labels: HW2

#628 jcr2211: Hw8
  students/jcr2211.md
Labels: HW8
