Repository ColumbiaOSS/project-proposals-s2023, pull requests merged in 2023-02, with the labels that each got.

#2 Added file with my UNI.
  aeg2225.md
Labels: HW0

#3 Create ek3192.md
  ek3192.md
Labels: HW0

#6 Create sg3790.md
  sg3790.md
Labels: HW0

#4 Create dh3116.md
  dh3116.md
Labels: HW0

#9 HW0: Create ew2664.md
  ew2664.md
Labels: HW0

#10 Add gds2133.md
  gds2133.md
Labels: HW0

#11 Add al4007.md
  al4007.md
Labels: HW0

#12 Create dag2226.md
  dag2226.md
Labels: HW0

#13 Add project proposal
  sip2109.md
Labels: HW0

#15 Add files via upload
  lhn2112.md
Labels: HW0

#17 Added Project Proposal and Contribution
  ma4338.md
Labels: HW0

#8 Add ea2905.md
  ea2905.md
Labels: HW0

#19 Added md file with personal info and proposal
  mws2170.md
Labels: HW0

#20 Create aj2604.md
  aj2604.md
Labels: HW0

#21 Create rjw2160.md
  rjw2160.md
Labels: HW0

#22 Created ag4219.md
  ag4219.md
Labels: HW0

#23 Create amz2145.md
  amz2145.md
Labels: HW0

#28 HW0 by zx2325
  zx2325.md
Labels: HW0

#29 Created mm5176.md
  mm5176.md
Labels: HW0

#32 kz2442
  kz2442.md
Labels: HW0

#33 Added uni file
  dme2136.md
Labels: HW0

#34 Create ala2201.md
  ala2201.md
Labels: HW0

#35 updated cl3945.md
  .github/CODEOWNERS
  cl3945.md
Labels: HW0

#37 kt2593
  kt2593.md
Labels: HW0

#38 Create tz2294.md
  tz2294.md
Labels: HW0

#41 Create jed2192.md
  jed2192.md
Labels: HW0

#44 Create grn2112.md
  grn2112.md
Labels: HW0

#45 sa3883
  sa3883.md
Labels: HW0

#5 Create eem2188.md
  eem2188.md
Labels: HW0

#24 nhc2117: HW0
  nhc2117.md
Labels: HW0

#30 mjk2244 HW0
  mjk2244.md
Labels: HW0

#31 HW0: ys3593 proposal
  ys3593.md
Labels: HW0

#40 Create fk2421.md
  fk2421.md
Labels: HW0

#49 created scb2197.m and filled it out accordingly
  scb2197.md
Labels: HW0

#50 Create be2246.md
  be2246.md
Labels: HW0

#51 Create kk3084.md
  kk3084.md
Labels: HW0

#53 Homework 0 submission
  los2119.md
Labels: HW0

#54 hw0B added file bs3243.md of project ideas and project contribution ideas
  bs3243.md
Labels: HW0

#57 Project/Contribution Proposals for Annie Song (afs2185)
  afs2185.md
Labels: HW0

#59 HW0B: imb2139
  imb2139.md
Labels: HW0

#62 Add project proposal for Yash
  yd2590.md
Labels: HW0

#63 Homework 0 TLG2141
  tlg2141.md
Labels: HW0

#64 Create sb4696.md
  sb4696.md
Labels: HW0

#65 Creates rp3111.md
  rp3111.md
Labels: HW0

#66 added jcr2211 project proposal
  jcr2211.md
Labels: HW0

#67 add project proposal
  yn2411.md
Labels: HW0

#68 Create an3056.md
  an3056.md
Labels: HW0

#73 adding proposal yva2002.md
  yva2002.md
Labels: HW0

#74 added yw3960.md
  yw3960.md
Labels: HW0

#75 Create smh2278.md
  smh2278.md
Labels: HW0

#78 Create cg3356.md
  cg3356.md
Labels: HW0

#79 HW0: sm4967
  sm4967.md
Labels: HW0

#76 Create pd2654.md
  pd2654.md
Labels: HW0

#80 Create eac2277.md
  eac2277.md
Labels: HW0

#81 llw2128.md
  llw2128.md
Labels: HW0

#82 HW0: ddn2115
  ddn2115.md
Labels: HW0

#85 Si2400 project proposal
  si2400.md
Labels: HW0

#94 Create cc4655.md
  cc4655.md
Labels: HW0

#100 HW0: Project Proposal (UNI: sst2147)
  sst2147.md
Labels: HW0

#107 Create es4060.md
  es4060.md
Labels: HW0

#110 Xinghang Sun
  xs2421.md
Labels: HW0

#111 create & update ac5003.md
  ac5003.md
Labels: HW0

#113 Create jp4013.md
  jp4013.md
Labels: HW0

#117 HW0: ss5945 Revised PR
  ss5945.md
Labels: HW0

#125 Adding HW0 project proposal for ss5946
  ss5946.md
Labels: HW0

#46 im2594-hw0
  im2594.md
Labels: HW0

#86 HW0 jm5025
  jm5025.md
Labels: HW0

#47 Project Proposal Ideas/Contribution Ideas Added
  dc3448.md
Labels: HW0

#48 added my markdown file with my project proposal and contributions
  cmg2249.md
Labels: HW0

#150 added oko2107.md for HW0
  oko2107.md
Labels: HW0

#119 hw0
  dz2428.md
Labels: HW0

#61 Create hj2589.md
  hj2589.md
Labels: HW0

#55 eo2464-hw0
  eo2464.md
Labels: HW0

#159 Create sn2865.md
  sn2865.md
Labels: HW0

#169 Hw0
  kk3528.md
Labels: HW0

#116 HW0: Create zx2413.md
  zx2413.md
Labels: HW0

#185 HW0: Project Proposal
  baa2159.md
Labels: HW0

#214 Create cn2521.md
  cn2521.md
Labels: HW0

#217 Create tr2721.md
  tr2721.md
Labels: HW0

#69 Update project proposal and project contributions
  tc3117.md
Labels: HW0

#226 HW0: committing my proposal
  st3443.md
Labels: HW0

#232 HW0
  ks3651.md
Labels: HW0

#101 my project proposal
  ntb2135.md
Labels: HW0

#188 HW0: add markdown file
  uyo2000.md
Labels: HW0

#196 HW0: kk3610
  kk3610.md
Labels: HW0

#18 Create tya2104.md
  tya2104.md
Labels: HW0

#243 HW0: Create wdw2117.md
  wdw2117.md
Labels: HW0

#245 Hw0(dh3027)
  dh3027.md
Labels: HW0

#247 move and cleanup some stragglers
  students/dh3027.md
  students/gt2453.md
  students/tya2104.md
  students/ua2182.md
  students/wdw2117.md
  students/yh3575.md
  students/yx2729.md
Labels: HW0, internal

#248 add conflicts for eem
  projects/python/pybaseball.md
Labels: HW2, internal

#236 HW2: Add project proposals
  projects/python/faker.md
  projects/python/mabby.md
  students/ew2664.md
Labels: HW2

#240 HW2: Resolved Conflict
  projects/python/numba.md
  projects/python/terminal-history.md
  students/ma4338.md
Labels: HW2

#244 HW2: Cleanup proposals for Yash by rebasing HW1 on main
  projects/python/pytorch.md
  projects/python/scikit-learn.md
  projects/python/txtai.md
  projects/scala/parquet4s.md
  projects/scala/shiva.md
  students/yd2590.md
Labels: HW2

#265 HW2
  projects/python/ez_scrape.md
  projects/python/faker.md
  students/dag2226.md
Labels: HW2

#252 HW2 - squash and resolve conflicts
  projects/cpp/AudioMoth.md
  projects/cpp/hybriddatastructures.md
  students/al4007.md
Labels: HW2

#251 HW2
  projects/python/copypaster.md
  projects/python/superstore.md
  students/aeg2225.md
Labels: HW2

#253 HW2: Rebased onto main branch
  projects/javascript/color-template.md
  projects/javascript/material-ui.md
  students/cl3945.md
Labels: HW2

#254 hw2 clear
  projects/cpp/shell-recorder.md
  projects/python/deep-speech.md
  students/yx2729.md
Labels: HW2

#256 HW2 jm5025
  projects/python/MC_Toolbox.md
  projects/python/PyScript.md
  students/jm5025.md
Labels: HW2

#268 HW2: cg3356
  projects/javascript/algorithm-lovers.md
  projects/python/theAlgorithms-Python.md
  students/cg3356.md
Labels: HW2

#171 add linting action
  .github/dependabot.yml
  .github/workflows/build.yml
  .markdownlint.json
  students/aeg2225.md
  students/al4007.md
  students/cg3356.md
  students/cl3945.md
  students/dag2226.md
  students/jm5025.md
  students/ma4338.md
  students/yd2590.md
  students/yx2729.md
Labels: internal

#273 add linter badge to readme
  README.md
Labels: internal

#266 HW2: ys3593
  projects/python/matplotlib.md
  projects/python/palettes.md
  students/ys3593.md
Labels: HW2

#261 HW2
  projects/python/matplotlib.md
  projects/python/no-teg.md
  students/ala2201.md
Labels: HW2

#291 HW2 ac5003
  projects/python/age3d.md
  projects/python/distributed.md
  students/ac5003.md
Labels: HW2

#298 HW2: kz2442 part 2 (new pull, please ignore my closed hw2 request)
  projects/python/pyvts.md
  projects/python/vtuberstudio.md
  students/kz2442.md
Labels: HW2

#301 HW2 sg3790 (all commits squashed)
  projects/python/interactive-score-editor.md
  projects/python/librosa.md
  students/sg3790.md
Labels: HW2

#310 HW2 mjk2244
  projects/python/pro-football-reference-web-scraper.md
  projects/python/pydfs-lineup-optimizer.md
  students/mjk2244.md
Labels: HW2

#311 HW2: Add repo link for rjw2160 project file
  projects/python/axiompy.md
  projects/python/objectify.md
  students/rjw2160.md
Labels: HW2

#302 HW0: create au2232.md
  students/au2232.md
Labels: HW0

#369 trigger some more conflicts
  mw3071.md
  students/ala2201.md
  students/au2232.md
  students/kz2442.md
  students/mjk2244.md
  students/mw3071.md
  students/sg3790.md
  students/ys3593.md
Labels: internal

#334 HW2 : [UNI:oko2107] squashed commits for hw2
  projects/python/mitiq.md
  projects/python/sec-web-scraper.md
  students/oko2107.md
Labels: HW2

#284 HW2 sm4967
  projects/javascript/snarkyjs.md
  projects/python/zkpy.md
  students/sm4967.md
Labels: HW2

#276 HW2: Add project link to smh2278.md, rebase with main
  projects/python/fundy.md
  projects/python/scrapy.md
  students/smh2278.md
Labels: HW2

#313 HW2: Adding in Rebased HW1 Commits for eem2188
  projects/python/pybaseball.md
  projects/python/usau-scraper.md
  students/eem2188.md
Labels: HW2

#282 HW 2: Update el3030.md after rebase
  projects/python/splitinerary.md
  students/el3030.md
Labels: HW2

#281 HW2: fix conflicts with rebase
  projects/python/dash.md
  projects/python/youtubecommentmanager.md
  students/nhc2117.md
Labels: HW2

#277 HW2
  projects/python/faker.md
  projects/typescript/tool-kit.md
  students/an3056.md
Labels: HW2

#241 HW2 (ea2905) Added custoplayer and jotai project proposals
  projects/javascript/custoplayer.md
  projects/javascript/jotai.md
  students/ea2905.md
Labels: HW2

#238 HW2
  projects/python/librosa.md
  projects/python/spotify-charts.md
  students/cc4655.md
Labels: HW2

#342 HW2 add link to AR Foundation Controllers repo
  projects/csharp/ARFoundation-controllers.md
  projects/python/transformers.md
  students/bs3243.md
Labels: HW2

#376 HW2: Rebase
  projects/javascript/calculator.md
  projects/python/notification.md
  students/ks3651.md
Labels: HW2

#379 Add lfc2136.md
  lfc2136.md
Labels: HW0

#287 HW2
  projects/python/numpy.md
  projects/python/spotify.md
  students/yy3131.md
Labels: HW2

#314 HW2: Rebase HW1 changes
  projects/python/matplotlib.md
  projects/python/polling-bot.md
  students/grn2112.md
Labels: HW2

#316 HW2: Rebase llw2128
  projects/python/CBSummary.md
  projects/python/matplotlib.md
  students/llw2128.md
Labels: HW2

#320 HW 2 aem2283 - file conflicts resolved
  projects/python/multi-scale-expansion.md
  projects/python/tensorflow.md
  students/aem2283.md
Labels: HW2

#325 HW2
  projects/python/forecast-weather.md
  projects/python/numpy.md
  students/ek3192.md
Labels: HW2

#329 HW2: dtw-sofar markdown and repo link added, eo2464.md reflects changes
  projects/python/clip.md
  projects/python/dtw-sofar.md
  projects/python/matplotlib.md
  projects/python/numpy.md
  projects/python/pytorch.md
  students/eo2464.md
Labels: HW2

#340 HW2
  projects/python/cabret.md
  projects/python/matplotlib.md
  students/imb2139.md
Labels: HW2

#347 HW2: Complete HW2 by rebasing HW1 changes
  projects/javascript/review-analysis-visualizer.md
  projects/python/pytorch.md
  students/be2246.md
Labels: HW2

#382 HW2: relative path fix
  projects/python/kms-encryption-tool.md
  projects/python/kubernetes.md
  projects/python/openverse-api.md
  projects/python/python-slack-sdk.md
  projects/python/zulip.md
  students/si2400.md
Labels: HW2

#384 HW2: Rebased and Fixed Conflicts
  projects/python/matplotlib.md
  projects/python/spotify_to_apple.md
  students/baa2159.md
Labels: HW2

#370 HW2
  projects/python/converter.md
  students/los2119.md
Labels: HW2

#385 HW2
  projects/javascript/reactnative.md
  projects/python/algoSolver.md
  students/ntb2135.md
Labels: HW2

#283 HW2: rebase
  projects/python/numpy.md
  projects/python/ranking.py.md
  students/sa3883.md
Labels: HW2

#285 HW2
  projects/javascript/freecodecamp.md
  projects/javascript/noobJS.md
  students/mws2170.md
Labels: HW2

#289 HW2
  projects/golang/kubernetes.md
  projects/python/fin-libs.md
  students/amz2145.md
Labels: HW2

#292 HW2: Rebase HW1 onto main branch
  projects/python/huggingface.md
  projects/python/image_augmentation.md
  students/kk3084.md
Labels: HW2

#293 HW2
  projects/javascript/diagramtocode.md
  projects/python/astropy.md
  students/sst2147.md
Labels: HW2

#306 HW2
  projects/javascript/svelteChess.md
  projects/python/pandas.md
  students/jcr2211.md
Labels: HW2

#362 HW2 - afs2185
  projects/cpp/SerenityOS.md
  projects/cpp/multithreading.md
  students/afs2185.md
Labels: HW2

#322 HW2: Rebase ag4219
  projects/javascript/chessjs.md
  projects/python/streeteasy-scraper.md
  students/ag4219.md
Labels: HW2

#354 HW2: Rebase and Squash
  projects/python/tone-reader.md
  projects/python/zulip.md
  students/ddn2115.md
Labels: HW2

#375 HW2: project idea and contribution choice files
  projects/python/pytest.md
  projects/python/sportsbox.md
  students/dh3116.md
Labels: HW2

#323 HW2: handled conflicts
  projects/python/geopandas.md
  projects/python/soccer-api-wrapper.md
  students/dme2136.md
Labels: HW2

#365 HW2
  projects/python/polygon.md
  projects/python/shapely.md
  students/dz2428.md
Labels: HW2

#308 HW2
  projects/python/cleanlab.md
  projects/python/clip_bbox.md
  students/gds2133.md
Labels: HW2

#377 HW2
  projects/python/conda.md
  projects/python/heracles.md
  students/gt2453.md
Labels: HW2

#336 HW2 hj2589
  projects/python/pydigree.md
  projects/python/pynrm.md
  students/hj2589.md
Labels: HW2
